version: '3.8'

services:
  dev-app:
    image: node:16.14.2
    build:
      context: dev-app
      target: builder
    working_dir: /app
    restart: always
    networks:
      - backnet
      - frontnet
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
      - ./dist:/app/dist
    command: bash -c "npm i --quiet --ignore-scripts && npm run start:dev"
    ports:
      - "8080:8080"
    labels:
      - "traefik.http.routers.dev-app.rule=Host(`api.weblinnk.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.dev-app.entrypoints=websecure"
      - "traefik.http.routers.dev-app.tls=true"
    # labels:
    #   - "traefik.http.routers.node-app.rule=Host(`api.weblinnk.com`)"
    #   - "traefik.http.routers.node-app.entrypoints=websecure"
    #   - "traefik.http.services.node-app.loadbalancer.server.port=8080"

  # proxy:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - dev-app
  #   networks:
  #     - frontnet
  traefik:
    image: traefik:v2.5
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "./traefik/acme.json:/etc/traefik/acme.json"

networks:
  backnet:
  frontnet:
