version: '3.8'

services:
  dev-app:
    image: node:16.14.2
    build:
      context: dev-app
      target: builder
    working_dir: /app
    restart: always
    networks:
      - proxy
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
      - ./dist:/app/dist
    command: bash -c "npm i --quiet --ignore-scripts && npm run start:dev"
    ports:
      - "8080:8080"
    labels:
      - "traefik.http.routers.dev-app.rule=Host(`api.weblinnk.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.dev-app.entrypoints=websecure"
      - "traefik.http.routers.dev-app.tls=true"
      - "traefik.http.routers.dev-app.tls.certresolver=http"
      - "traefik.http.routers.dev-app.service=dev-app"
      - "traefik.http.services.dev-app.loadbalancer.server.port=8080"

  traefik:
    image: traefik:v2.5
    restart: always
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CLOUDFLARE_EMAIL=rotondwamulelu@gmail.com
      - CLOUDFLARE_API_KEY=Mnxp9RGHG3s55H5zgnNRbXHMhZQO0fA33acJiPgi
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml"
      - "./traefik/acme.json:/etc/traefik/acme.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik.weblinnk.com`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=username:hashed-password"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.weblinnk.com`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true