api:
  dashboard: true

entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: rotondwamulelu@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: web

  cloudflare:
    acme:
      email: rotondwamulelu@gmail.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers: [1.1.1.1:53, 1.0.0.1:53]
        delayBeforeCheck: 0
